server:
  port: 8081

ftp:
  host: image.franxx.top
  port: 21
  username: ftpuser
  password: 111111
  basePath: /home/ftpuser/www/images
  imagBaseUrl: http://image.franxx.top/images

spring:
  datasource:
    url: jdbc:mysql://47.103.53.243:3306/blog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
    #错误直接抛出异常
    #    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  freemarker:
    cache: false
    request-context-attribute: request
  mybatis:
    config-location: classpath:mybatis-cfg.xml
    mapper-locations: classpath:top/franxx/blog/mapper/*.xml
  spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
